spring:
  application:
    name: catalog-service
  freemarker:
     enabled: false
server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    leaseRenewalIntervalInSeconds : 3